INSERT INTO brands (name, description, created_at, updated_at)
VALUES ('Toyota', 'Japanese automotive manufacturer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Volkswagen', 'German automotive manufacturer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Mercedes-Benz', 'German global automobile marque', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('BMW', 'German multinational company producing luxury vehicles', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Honda', 'Japanese public multinational conglomerate', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Ford', 'American multinational automaker', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Nissan', 'Japanese multinational automobile manufacturer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Audi', 'German automotive manufacturer of luxury vehicles', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Hyundai', 'South Korean multinational automotive manufacturer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Kia', 'South Korean multinational automotive manufacturer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Chevrolet', 'American automobile division of General Motors (GM)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Porsche', 'German automobile manufacturer specializing in high-performance sports cars', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Lexus', 'Luxury vehicle division of Toyota', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Subaru', 'Japanese automotive manufacturing division of Subaru Corporation', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
       ('Mazda', 'Japanese multinational automaker', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Jeep', 'American automobile marque, now owned by Stellantis', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Land Rover', 'British brand of predominantly four-wheel drive, off-road capable vehicles', CURRENT_TIMESTAMP,    CURRENT_TIMESTAMP),
       ('Volvo', 'Swedish multinational manufacturing company', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Ferrari', 'Italian luxury sports car manufacturer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Lamborghini', 'Italian brand and manufacturer of luxury sports cars and SUVs', CURRENT_TIMESTAMP,        CURRENT_TIMESTAMP),
       ('Tesla', 'American electric vehicle and clean energy company', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Peugeot', 'French automotive manufacturer, part of Stellantis', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Renault', 'French multinational automobile manufacturer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Citroën', 'French automobile manufacturer, part of Stellantis', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Fiat', 'Italian automobile manufacturer, part of Stellantis', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Skoda', 'Czech automobile manufacturer, subsidiary of Volkswagen Group', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('SEAT', 'Spanish automobile manufacturer, subsidiary of Volkswagen Group', CURRENT_TIMESTAMP,  CURRENT_TIMESTAMP),
       ('Mitsubishi', 'Japanese multinational automotive manufacturer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Suzuki', 'Japanese multinational corporation', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Jaguar', 'Luxury vehicle brand of Jaguar Land Rover', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Cadillac', 'American luxury automobile marque owned by General Motors', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Buick', 'American automobile brand owned by General Motors', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('GMC', 'American brand of trucks, SUVs, vans, and light-duty trucks, owned by General Motors', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Chrysler', 'American luxury car brand, part of Stellantis', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Dodge', 'American brand of automobiles and a division of Stellantis', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Ram', 'American brand of light to mid-weight commercial vehicles, division of Stellantis', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('Acura', 'Luxury vehicle division of Honda', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Infiniti', 'Luxury vehicle division of Nissan', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Genesis', 'Luxury vehicle division of Hyundai', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Rolls-Royce', 'British luxury automobile maker', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Bentley', 'British manufacturer and marketer of luxury cars and SUVs', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Maserati', 'Italian luxury vehicle manufacturer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Alfa Romeo', 'Italian premium car manufacturer, part of Stellantis', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Mini', 'British automotive marque owned by BMW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Smart', 'German automotive marque and division of Daimler AG', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Opel', 'German automobile manufacturer, subsidiary of Stellantis', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Vauxhall', 'British car brand, subsidiary of Stellantis (operates as Opel in UK)', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('DS Automobiles', 'French premium automotive marque, part of Stellantis', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Lancia', 'Italian car manufacturer, part of Stellantis', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Alpine', 'French manufacturer of racing and sports cars', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Polestar', 'Swedish automotive brand owned by Volvo Cars and Geely', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Rivian', 'American electric vehicle automaker and automotive technology company', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('Lucid Motors', 'American electric vehicle manufacturer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('BYD', 'Chinese multinational manufacturing company (Build Your Dreams)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Geely', 'Chinese multinational automotive company', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Great Wall Motors (GWM)', 'Chinese automobile manufacturer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Chery', 'Chinese state-owned automobile manufacturer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('SAIC Motor', 'Chinese state-owned automotive design and manufacturing company', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('Tata Motors', 'Indian multinational automotive manufacturing company', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Mahindra & Mahindra', 'Indian multinational automotive manufacturing corporation', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('Isuzu', 'Japanese commercial vehicle and diesel engine manufacturing company', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('McLaren', 'British automotive manufacturer of luxury, high-performance sports cars', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('Bugatti', 'French high-performance luxury automobiles manufacturer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Pagani', 'Italian manufacturer of sports cars and carbon fiber components', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('Koenigsegg', 'Swedish manufacturer of high-performance sports cars', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Aston Martin', 'British manufacturer of luxury sports cars and grand tourers', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('Lotus', 'British automotive company that manufactures sports cars and racing cars', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('VinFast', 'Vietnamese automotive manufacturer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('SsangYong', 'South Korean automobile manufacturer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Dacia', 'Romanian car manufacturer, subsidiary of Renault', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Lada', 'Russian car manufacturer, part of AvtoVAZ', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Proton', 'Malaysian automotive company', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Perodua', 'Malaysian second largest automobile manufacturer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Holden', 'Australian EOL car brand, formerly GM subsidiary', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    ON CONFLICT (name) DO NOTHING;



INSERT INTO models (brand_id, name, description, created_at, updated_at)
VALUES
-- Sedanes y Hatchbacks
(1, 'Corolla', 'Coche compacto, múltiples generaciones', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'Camry', 'Coche mediano, múltiples generaciones', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'Avalon', 'Coche grande (hasta ~2022)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'Prius', 'Coche híbrido eléctrico, modelo pionero', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'Yaris', 'Coche subcompacto (también conocido como Vitz)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'Echo', 'Coche subcompacto (principios de los 2000)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'Matrix', 'Hatchback/wagon compacto (relacionado con Corolla)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'Crown', 'Sedán/crossover grande (reintroducido en algunos mercados)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'Mirai', 'Vehículo de pila de combustible de hidrógeno', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'Celica', 'Coche deportivo compacto (hasta ~2006)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'GR Corolla', 'Versión de alto rendimiento del Corolla', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'Prius Prime', 'Versión híbrida enchufable del Prius', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- SUVs y Crossovers
(1, 'RAV4', 'SUV crossover compacto, muy popular', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'Highlander', 'SUV crossover mediano', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '4Runner', 'SUV mediano sobre bastidor, capacidad todoterreno', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'Sequoia', 'SUV grande', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'Land Cruiser', 'SUV de lujo grande, todoterreno', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'FJ Cruiser', 'SUV compacto de estilo retro (hasta ~2014 en EE.UU., más tiempo en otros lugares)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'Venza', 'SUV crossover mediano (dos generaciones en este periodo)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'C-HR', 'SUV crossover subcompacto', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'bZ4X', 'SUV crossover compacto eléctrico de batería', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'Corolla Cross', 'SUV crossover compacto basado en el Corolla', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'Grand Highlander', 'Versión más grande del Highlander', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'RAV4 Prime', 'Versión híbrida enchufable del RAV4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Camionetas (Pickup Trucks - consideradas transporte personal)
(1, 'Tacoma', 'Camioneta pickup mediana, popular para uso personal', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'Tundra', 'Camioneta pickup grande, popular para uso personal', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Minivans
(1, 'Sienna', 'Monovolumen (Minivan)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Deportivos
(1, 'Supra', 'Coche deportivo (reintroducido como GR Supra)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'MR2 Spyder', 'Deportivo de motor central (hasta ~2007)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '86 / GR86', 'Coche deportivo (desarrollado con Subaru)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Hatchbacks y Sedanes
(2, 'Golf', 'Coche compacto icónico, múltiples generaciones', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Polo', 'Coche supermini, muy popular en Europa', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Jetta', 'Sedán compacto', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Passat', 'Coche mediano, variantes sedán y familiar (station wagon)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Beetle', 'New Beetle / Beetle (A5), diseño retro (hasta ~2019)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Lupo', 'Coche urbano (principios de los 2000)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Fox', 'Coche urbano / Supermini', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Up!', 'Coche urbano', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Phaeton', 'Sedán de lujo grande (hasta ~2016)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Bora', 'Sedán compacto (nombre usado para Jetta en algunos mercados)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Arteon', 'Sedán liftback mediano / Shooting Brake', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'ID.3', 'Hatchback compacto eléctrico', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Golf GTI', 'Versión deportiva del Golf', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Golf R', 'Versión de alto rendimiento del Golf', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Scirocco', 'Coupé deportivo compacto (tercera generación ~2008-2017)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Eos', 'Coupé cabriolet compacto (hasta ~2015)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- SUVs y Crossovers
(2, 'Tiguan', 'SUV crossover compacto', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Touareg', 'SUV de lujo mediano', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Atlas', 'SUV mediano (principalmente Norteamérica, también Teramont)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'T-Roc', 'SUV crossover subcompacto', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'T-Cross', 'SUV crossover subcompacto (más pequeño que T-Roc)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Taos', 'SUV crossover compacto', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'ID.4', 'SUV crossover compacto eléctrico', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'ID.5', 'SUV crossover compacto eléctrico (versión coupé del ID.4)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Tiguan Allspace', 'Versión de batalla larga del Tiguan', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- MPVs / Monovolúmenes
(2, 'Touran', 'Monovolumen compacto (MPV)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Sharan', 'Monovolumen grande (MPV)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Golf Sportsvan', 'Monovolumen compacto basado en el Golf (también Golf Plus)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'ID. Buzz', 'Monovolumen / Furgoneta de pasajeros eléctrica (diseño retro)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Furgonetas Ligeras (versiones de pasajeros)
(2, 'Multivan', 'Versión de pasajeros de la furgoneta Transporter', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Caravelle', 'Versión de pasajeros de la furgoneta Transporter (a menudo para transporte de personas)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'California', 'Versión camper de la furgoneta Transporter', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Caddy Life', 'Versión de pasajeros del Caddy (Vehículo de Actividad Recreativa)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Camioneta (Pickup Truck - considerada transporte personal)
(2, 'Amarok', 'Camioneta pickup mediana, popular para uso personal', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)


    ON CONFLICT (name) DO NOTHING;